### ISSUE TITLE
Error when going to older pages

### ISSUE THREAD

**Issue by Rjected** [ethpandaops/dora#81]
I was looking at the devnet-1 explorer and it was not able to get past page 6, with this URL
https://dora.pectra-devnet-1.ethpandaops.io/slots?s=1855&c=50

This had the following error:
```


URL: /slots?s=1855&c=50
Time: 2024-07-23 18:00:52.262374727 +0000 UTC m=+908.117313918
Version: git-fbf266b

Error:
page call 125 panic: reflect: reflect.Value.Set using unaddressable value

Stack Trace:
goroutine 11807 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/ethpandaops/dora/services.(*FrontendCacheService).processPageCall.func1.1()
	/home/runner/work/dora/dora/services/frontendcache.go:122 +0xd4
panic({0x15a3440?, 0xc00b1a2c90?})
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/panic.go:914 +0x21f
reflect.flag.mustBeAssignableSlow(0xc00b0a3960?)
	/opt/hostedtoolcache/go/1.21.12/x64/src/reflect/value.go:272 +0x74
reflect.flag.mustBeAssignable(...)
	/opt/hostedtoolcache/go/1.21.12/x64/src/reflect/value.go:259
reflect.Value.Set({0x1759300?, 0x0?, 0x41b4a8?}, {0x1759300?, 0xc00b0a3960?, 0xc0092175e8?})
	/opt/hostedtoolcache/go/1.21.12/x64/src/reflect/value.go:2254 +0x65
github.com/pk910/dynamic-ssz.(*DynSsz).unmarshalType(0xc0092176d8, {0x1e3f0c8, 0x1759300}, {0x1759300?, 0x0?, 0x16a1e60?}, {0xc0002c3600, 0xcc5, 0xd80}, {0xc009217630, ...}, ...)
	/home/runner/go/pkg/mod/github.com/pk910/dynamic-ssz@v0.0.4/unmarshal.go:47 +0x198
github.com/pk910/dynamic-ssz.(*DynSsz).UnmarshalSSZ(0x1844451?, {0x1759300?, 0x0?}, {0xc0002c3600?, 0xcc5, 0x2c?})
	/home/runner/go/pkg/mod/github.com/pk910/dynamic-ssz@v0.0.4/dynssz.go:106 +0xe6
github.com/ethpandaops/dora/indexer.UnmarshalVersionedSignedBeaconBlockSSZ(0x6, {0xc0002c3600, 0xcc5, 0xd80})
	/home/runner/work/dora/dora/indexer/ssz_helper.go:104 +0x3a6
github.com/ethpandaops/dora/indexer.(*CacheBlock).GetBlockBody(0xc0076b4fc0)
	/home/runner/work/dora/dora/indexer/cache_block.go:155 +0x135
github.com/ethpandaops/dora/indexer.buildDbBlock(0xc0076b4fc0, 0xc00a6bd970)
	/home/runner/work/dora/dora/indexer/write_db.go:176 +0x32
github.com/ethpandaops/dora/indexer.(*Indexer).BuildLiveBlock(0x28feea0?, 0xc0076b4fc0)
	/home/runner/work/dora/dora/indexer/indexer.go:680 +0x17c
github.com/ethpandaops/dora/services.(*ChainService).GetDbBlocksForSlots(0xc000158fc0, 0x73f, 0x32, 0x1, 0x1)
	/home/runner/work/dora/dora/services/chainservice_blocks.go:347 +0xa6c
github.com/ethpandaops/dora/handlers.buildSlotsPageData(0x73f, 0x32)
	/home/runner/work/dora/dora/handlers/slots.go:124 +0x327
github.com/ethpandaops/dora/handlers.getSlotsPageData.func1(0xc00b0d5b80)
	/home/runner/work/dora/dora/handlers/slots.go:57 +0x25
github.com/ethpandaops/dora/services.(*FrontendCacheService).processPageCall.func1(0x1c608e8?)
	/home/runner/work/dora/dora/services/frontendcache.go:137 +0x1de
created by github.com/ethpandaops/dora/services.(*FrontendCacheService).processPageCall in goroutine 10126
	/home/runner/work/dora/dora/services/frontendcache.go:116 +0x2b4

```

Now it says `503 Service Temporarily Unavailable`, I hope I didn't break it!

**Comment by Rjected** [comment]
works now!
